theme: jekyll-theme-slate
title: Presentations | Online Presenations Are Here.
description: Present to you, A little of my skills as a web based  Presenation.


show_downloads: true
gem "github-pages", group: :jekyll_plugins
